env:
  es6: true
  node: true
  mocha: true
  commonjs: true
  browser: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaVersion: 8
globals:
  conf: true
  RedisRefError: true
  InvalidArgsGeneralityError: true
  ArgsGeneralityError: true
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars:
    - warn
  no-console:
    - off
